# question https://leetcode.com/problems/find-the-difference/description/
'''
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''
# talen test_ok
# TODO: reduce time spend
class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        t1=[0]*26
        t2=[0]*26
        ch=''
        for k in s:
            t1[ord(k)-97]+=1
        for k in t:
            t2[ord(k)-97]+=1
        for i in range(26):
            if t2[i]-t1[i]==1:
                ch=chr(97+i)
                break
        return ch


m=Solution()
s = "abcd"
t = "abcde"
print(m.findTheDifference(s,t))
